### ISSUE TITLE
Option for non minified source code in docs

### ISSUE THREAD

**Issue by pehrlich2** [Typeform/embed#600]
Hello!

Trying to work in a vanilla embed and I'm getting an error.  However I can't really troubleshoot as the code is minified.  Would be great if there was an easy way to link to, a dev version something like this:  `embed.typeform.com/next/embed.dev.js`

If you're curious, this is an error. If I have time I'll see if I can find it and fix it. 

```
embed.js:1 Uncaught DOMException: Failed to execute 'setAttribute' on 'Element': '0' is not a valid attribute name.
    at http://embed.typeform.com/next/embed.js:1:35746
    at Array.forEach (<anonymous>)
    at t.addAttributesToElement (http://embed.typeform.com/next/embed.js:1:35723)
    at t.createIframe (http://embed.typeform.com/next/embed.js:1:40672)
    at t.createWidget (http://embed.typeform.com/next/embed.js:1:21358)
    at emailChange (http://localhost:1313/?:368:15)
    at HTMLInputElement.onchange (http://localhost:1313/?#signup:219:33)
```

**Comment by mathio** [comment]
Thank you for the suggestion 👍

**Comment by mathio** [comment]
The  production JS file is built by Webpack. The file is not intended to be read by humans, as it is transformed even if it is not minified.

To debug code built by Webpack we can use [source maps](https://blog.teamtreehouse.com/introduction-source-maps). However we do not deploy full SDK code to production, so we can not provide source maps at the moment. The only way to use sourcemaps in you project is to clone this repo locally and build the sources yourself (`yarn build`). 

You will see errors like this, if it helps:

```
add-attributes-to-element.ts:8 Uncaught DOMException: Failed to execute 'setAttribute' on 'Element': '0' is not a valid attribute name.
    at eval (webpack://tf/./src/utils/add-attributes-to-element.ts?:8:17)
    at Array.forEach (<anonymous>)
    at addAttributesToElement (webpack://tf/./src/utils/add-attributes-to-element.ts?:7:24)
    at createIframe (webpack://tf/./src/utils/create-iframe/create-iframe.ts?:21:36)
    at Object.createWidget (webpack://tf/./src/factories/create-widget/create-widget.ts?:55:39)
    at http://localhost:9090/widget-js.html:35:17
    ```
