### ISSUE TITLE
Raise on incorrect argument types

### ISSUE THREAD

**Issue by pehrlich2** [Typeform/embed#601]
When converting code from data- attributes to object attributes, it's easy to get the types wrong.  E.g., by passing in a string for `iframeProps` or `hidden` instead of an onbject.  When this happens, a typeerror is not thrown, but this piece of confusion instead:

```
embed.js:1 Uncaught DOMException: Failed to execute 'setAttribute' on 'Element': '0' is not a valid attribute name.
    at http://embed.typeform.com/next/embed.js:1:35746
    at Array.forEach (<anonymous>)
    at t.addAttributesToElement (http://embed.typeform.com/next/embed.js:1:35723)
    at t.createIframe (http://embed.typeform.com/next/embed.js:1:40672)
    at t.createWidget (http://embed.typeform.com/next/embed.js:1:21358)
    at emailChange (http://localhost:1313/?:368:15)
    at HTMLInputElement.onchange (http://localhost:1313/?#signup:219:33)
```

Thanks

**Comment by mathio** [comment]
Thank you for _raising_ this, we will have a look 😄

**Comment by pehrlich2** [comment]
:)  small aside - on the docs for that page it says "optinos" once instead of "options"!

**Comment by mathio** [comment]
@pehrlich2 I was unable to reproduce this. Can you please provide a reproducible example?
